

CREATE PROCEDURE [dbo].[GENERATE_DIM_MOLECULE]
AS
BEGIN

declare @count int
select @count=count(*) from [dbo].[RAW_TDW-ECP_DIM_MOLECULE]

if @count > 0 
begin
	UPDATE [dbo].[RAW_TDW-ECP_DIM_MOLECULE]
	SET SYNONYM=0
	WHERE SYNONYM IS NULL

	UPDATE [dbo].[RAW_TDW-ECP_DIM_MOLECULE]
	SET PARENT=0
	WHERE PARENT IS NULL

	MERGE [dbo].[DMMolecule] AS TARGET
	USING [dbo].[RAW_TDW-ECP_DIM_MOLECULE] AS SOURCE
	ON (TARGET.FCC=SOURCE.FCC AND TARGET.[MOLECULE]=SOURCE.[MOLECULE])
	WHEN MATCHED
	THEN
	UPDATE SET TARGET.CHANGE_FLAG =
		CASE
			WHEN CAST(TARGET.[FCC] AS VARCHAR(30))+' '+CAST(TARGET.[MOLECULE] AS VARCHAR(30))+' '+TARGET.[DESCRIPTION]=CAST(SOURCE.[FCC] AS VARCHAR(30))+' '+CAST(SOURCE.[MOLECULE] AS VARCHAR(30))+' '+SOURCE.[DESCRIPTION]
			THEN 'U'
			WHEN CAST(TARGET.[FCC] AS VARCHAR(30))+' '+CAST(TARGET.[MOLECULE] AS VARCHAR(30))+' '+TARGET.[DESCRIPTION]<>CAST(SOURCE.[FCC] AS VARCHAR(30))+' '+CAST(SOURCE.[MOLECULE] AS VARCHAR(30))+' '+SOURCE.[DESCRIPTION]
			THEN 'M'
		END
		,TARGET.[SYNONYM]=SOURCE.[SYNONYM]
		,TARGET.[PARENT]=SOURCE.[PARENT]
		,TARGET.[DESCRIPTION]=SOURCE.[DESCRIPTION]
		,TARGET.[TIME_STAMP]=GETDATE()
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (FCC, MOLECULE, SYNONYM, PARENT, DESCRIPTION, CHANGE_FLAG, TIME_STAMP)
		VALUES(SOURCE.FCC, SOURCE.MOLECULE, SOURCE.SYNONYM, SOURCE.PARENT, DESCRIPTION,'A',GETDATE())

	WHEN NOT MATCHED BY SOURCE THEN
		UPDATE SET TARGET.CHANGE_FLAG='D',
		TARGET.[TIME_STAMP]=GETDATE();


	--INSERT INTO  [dbo].[HISTORY_TDW-ECP_DIM_MOLECULE] 
	--SELECT FCC, MOLECULE, SYNONYM, PARENT, DESCRIPTION, CHANGE_FLAG, TIME_STAMP FROM [dbo].[TDW-ECP_DIM_MOLECULE]
	--WHERE CHANGE_FLAG<>'U'

	--UPDATE A SET A.TIME_STAMP=B.TIME_STAMP FROM [dbo].[TDW-ECP_DIM_MOLECULE] A
	--INNER JOIN (
	--SELECT
	--	 FCC, MOLECULE, SYNONYM, PARENT, DESCRIPTION,
	--	 [CHANGE_FLAG], MIN(TIME_STAMP)AS TIME_STAMP
	--FROM [dbo].[HISTORY_TDW-ECP_DIM_MOLECULE]
	--WHERE CHANGE_FLAG='D' 
	--GROUP BY FCC, MOLECULE, SYNONYM, PARENT, DESCRIPTION,CHANGE_FLAG) B
	--ON A.FCC=B.FCC AND A.MOLECULE=B.MOLECULE
	--WHERE A.CHANGE_FLAG='D' AND B.CHANGE_FLAG='D'

	--;With CTE
	--AS
	--(
	--SELECT *,ROW_NUMBER ()OVER(PARTITION BY FCC,MOLECULE ORDER BY FCC,MOLECULE, TIME_STAMP ASC) Cnt 
	--FROM [dbo].[HISTORY_TDW-ECP_DIM_MOLECULE] WHERE  CHANGE_FLAG='D'
	--)
	--DELETE FROM CTE WHERE Cnt>1



	INSERT INTO  [dbo].[HISTORY_TDW-ECP_DIM_MOLECULE]
	SELECT DISTINCT
		M.FCC AS FCC,
		P.PACK_DESCRIPTION AS [PACK_DESCRIPTION],
		'M' AS [CHANGE_FLAG],
		M.TIME_STAMP AS [TIME_STAMP]
	FROM [DMMolecule] M
	INNER JOIN [DIMProduct_Expanded] P
	ON M.FCC=P.FCC
	WHERE P.FCC IN (SELECT DISTINCT FCC FROM [DMMolecule] WHERE CHANGE_FLAG='M')


	UPDATE A SET A.TIME_STAMP=B.TIME_STAMP FROM [dbo].[DMMolecule] A
	INNER JOIN (
	SELECT
		 FCC, PACK_DESCRIPTION, [CHANGE_FLAG], MIN(TIME_STAMP)AS TIME_STAMP
	FROM [dbo].[HISTORY_TDW-ECP_DIM_MOLECULE]
	WHERE CHANGE_FLAG='M' 
	GROUP BY FCC, PACK_DESCRIPTION, [CHANGE_FLAG]) B
	ON A.FCC=B.FCC
	WHERE A.CHANGE_FLAG='M' AND B.CHANGE_FLAG='M'

	;With CTE
	AS
	(
	SELECT *,ROW_NUMBER ()OVER(PARTITION BY FCC,PACK_DESCRIPTION ORDER BY FCC,PACK_DESCRIPTION, TIME_STAMP ASC) Cnt 
	FROM [dbo].[HISTORY_TDW-ECP_DIM_MOLECULE] WHERE  CHANGE_FLAG='M'
	)
	DELETE FROM CTE WHERE Cnt>1

	EXEC [CreateDMMoleculeConcat]
end

END






