//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.EverestPortal.API.Models.Report
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ReportSection")]
    public partial class ReportSection
    {

        public int ReportSectionID { get; set; }
        public string ReportSectionName { get; set; }
        public int UserTypeID { get; set; }
    }
}
