
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.EverestPortal.API
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ReportFieldList")]
    public partial class ReportFieldList
    {
        [Key]
        public int FieldID { get; set; }
        public string FieldName { get; set; }
        public string FieldDescription { get; set; }
        public string TableName { get; set; }

        public string FieldType { get; set; }
    }
}
