
CREATE PROCEDURE [SERVICE].[CREATE_AU9_CLIENT_TERR]
AS
BEGIN


TRUNCATE TABLE [SERVICE].[AU9_CLIENT_TERR_RAW]

EXECUTE [SERVICE].[CREATE_CT_LVL1]
EXECUTE [SERVICE].[CREATE_CT_LVL2]
EXECUTE [SERVICE].[CREATE_CT_LVL3]
EXECUTE [SERVICE].[CREATE_CT_LVL4]
EXECUTE [SERVICE].[CREATE_CT_LVL5]
EXECUTE [SERVICE].[CREATE_CT_LVL6]
EXECUTE [SERVICE].[CREATE_CT_LVL7]
EXECUTE [SERVICE].[CREATE_CT_LVL8]


TRUNCATE TABLE [SERVICE].[AU9_CLIENT_TERR]
INSERT INTO [SERVICE].[AU9_CLIENT_TERR]

SELECT
	 X.CLIENT_TERR_ID
	,'1' AS [CLIENT_TERR_VERS_NBR]
	,X.OUTLET
	,X.LVL_1_TERR_NM
	,Y.LVL_1_TERR_CD
	,X.LVL_2_TERR_NM
	,Y.LVL_2_TERR_CD
	,X.LVL_3_TERR_NM
	,Y.LVL_3_TERR_CD
	,X.LVL_4_TERR_NM
	,Y.LVL_4_TERR_CD
	,X.LVL_5_TERR_NM
	,Y.LVL_5_TERR_CD
	,X.LVL_6_TERR_NM
	,Y.LVL_6_TERR_CD
	,X.LVL_7_TERR_NM
	,Y.LVL_7_TERR_CD
	,X.LVL_8_TERR_NM
	,Y.LVL_8_TERR_CD
FROM 
	(
	SELECT 
		 TERRITORY_ID AS [CLIENT_TERR_ID]
		,OUTLET_CODE AS OUTLET
		,[LVL_1_TERR_NM]
		,[LVL_2_TERR_NM]
		,[LVL_3_TERR_NM]
		,[LVL_4_TERR_NM]
		,[LVL_5_TERR_NM]
		,[LVL_6_TERR_NM]
		,[LVL_7_TERR_NM]
		,[LVL_8_TERR_NM]
	FROM (SELECT [TERRITORY_ID]
		  ,[NODE_NAME]
		  ,[TYPE]
		  ,[OUTLET_CODE], LEVEL_NM FROM [SERVICE].[AU9_CLIENT_TERR_RAW]) P
	PIVOT
		(
		MAX (NODE_NAME)
		FOR LEVEL_NM IN
			([LVL_1_TERR_NM],[LVL_2_TERR_NM],[LVL_3_TERR_NM],[LVL_4_TERR_NM],[LVL_5_TERR_NM],[LVL_6_TERR_NM],[LVL_7_TERR_NM],[LVL_8_TERR_NM]
			)
		) AS PVT
	)  X
	JOIN
	(
	SELECT 
		 TERRITORY_ID AS [CLIENT_TERR_ID]
		 ,OUTLET_CODE AS OUTLET
		,[LVL_1_TERR_CD]
		,[LVL_2_TERR_CD]
		,[LVL_3_TERR_CD]
		,[LVL_4_TERR_CD]
		,[LVL_5_TERR_CD]
		,[LVL_6_TERR_CD]
		,[LVL_7_TERR_CD]
		,[LVL_8_TERR_CD]

	FROM (SELECT [TERRITORY_ID]
		  ,NODE_CODE
		  ,[TYPE]
		  ,[OUTLET_CODE], LEVEL_CD FROM [ECP_TO_TDW].[STAGE].[CLIENT_TERR_RAW]) P

	PIVOT
		(
		MAX (NODE_CODE)
		FOR LEVEL_CD IN
			([LVL_1_TERR_CD],[LVL_2_TERR_CD],[LVL_3_TERR_CD],[LVL_4_TERR_CD],[LVL_5_TERR_CD],[LVL_6_TERR_CD],[LVL_7_TERR_CD],[LVL_8_TERR_CD])
		) AS PVT
	) Y
ON X.CLIENT_TERR_ID=Y.CLIENT_TERR_ID and X.OUTLET=Y.OUTLET

END




