CREATE TABLE [SERVICE].[AU9_CLIENT_TERR_RAW] (
    [GROUP_ID]      INT            NOT NULL,
    [PARENT_ID]     INT            NULL,
    [ROOT_GROUP_ID] INT            NULL,
    [GROUP_NAME]    NVARCHAR (MAX) NULL,
    [LEVEL_NUMBER]  NVARCHAR (MAX) NULL,
    [LEVEL_CD]      NVARCHAR (MAX) NULL,
    [LEVEL_NM]      NVARCHAR (MAX) NULL,
    [GROUP_NUMBER]  NVARCHAR (MAX) NULL,
    [TERRITORY_ID]  INT            NULL,
    [NODE_CODE]     NVARCHAR (MAX) NULL,
    [NODE_NAME]     NVARCHAR (MAX) NULL,
    [TYPE]          NVARCHAR (MAX) NULL,
    [OUTLET_CODE]   NVARCHAR (MAX) NULL
);

