CREATE TABLE [SERVICE].[AU9_CLIENT_TERR_TYP] (
    [CLIENT_TERR_ID]       BIGINT       NULL,
    [CLIENT_ID]            INT          NULL,
    [CLIENT_TERR_VERS_NBR] INT          NULL,
    [LVL_1_TERR_TYP_NM]    VARCHAR (50) NULL,
    [LVL_2_TERR_TYP_NM]    VARCHAR (50) NULL,
    [LVL_3_TERR_TYP_NM]    VARCHAR (50) NULL,
    [LVL_4_TERR_TYP_NM]    VARCHAR (50) NULL,
    [LVL_5_TERR_TYP_NM]    VARCHAR (50) NULL,
    [LVL_6_TERR_TYP_NM]    VARCHAR (50) NULL,
    [LVL_7_TERR_TYP_NM]    VARCHAR (50) NULL,
    [LVL_8_TERR_TYP_NM]    VARCHAR (50) NULL,
    [TERR_LOWEST_LVL_NBR]  VARCHAR (30) NULL,
    [RPTG_LVL_RSTR]        VARCHAR (50) NULL
);

