export const PackSearchColumns: any[] = [
    { colName: "PFC", colText: "PFC", sortable: true, sorted: false, visible: true },
    { colName: "Pack_Description", colText: "Pack Description", sortable: true, sorted: true, visible: true },
    { colName: "ProductName", colText: "Product Description", sortable: true, sorted: false, visible: true },
    { colName: "Org_Long_Name", colText: "Manufacturer", sortable: true, sorted: false, visible: true },
    { colName: "ATC4_Desc", colText: "ATC4", sortable: true, sorted: false, visible: true },
    { colName: "NEC4_Desc", colText: "NEC4", sortable: true, sorted: false, visible: true },
    { colName: "Molecules", colText: "Molecules", sortable: false, sorted: false, visible: true },
    { colName: "FRM_Flgs5_Desc", colText: "Flagging", sortable: true, sorted: false, visible: true },
    { colName: "Frm_Flgs3_Desc", colText: "Branding", sortable: true, sorted: false, visible: true },
    { colName: "APN", colText: "APN/EAN/GTIN (barcode)", sortable: true, sorted: false, visible: true },

    { colName: "PackID", colText: "Pack ID", sortable: true, sorted: false, visible: false },
    { colName: "Prod_cd", colText: "Prod Code", sortable: true, sorted: false, visible: false },
    { colName: "Pack_cd", colText: "Pack Code", sortable: true, sorted: false, visible: false },
    
    
    { colName: "Product_Long_Name", colText: "Product Long Name", sortable: true, sorted: false, visible: false },
    { colName: "FCC", colText: "FCC", sortable: true, sorted: false, visible: false },

    { colName: "ATC1_Code", colText: "ATC1 Code", sortable: true, sorted: false, visible: false },
    { colName: "ATC1_Desc", colText: "ATC1 Desc", sortable: true, sorted: false, visible: false },
    { colName: "ATC2_Code", colText: "ATC2 Code", sortable: true, sorted: false, visible: false },
    { colName: "ATC2_Desc", colText: "ATC2 Desc", sortable: true, sorted: false, visible: false },
    { colName: "ATC3_Code", colText: "ATC3 Code", sortable: true, sorted: false, visible: false },
    { colName: "ATC3_Desc", colText: "ATC3 Desc", sortable: true, sorted: false, visible: false },
    { colName: "ATC4_Code", colText: "ATC4 Code", sortable: true, sorted: false, visible: false },
    //{ colName: "ATC4_Desc", colText: "ATC4 Code", sortable: true, sorted: false, visible: false },

    { colName: "NEC1_Code", colText: "NEC1 Code", sortable: true, sorted: false, visible: false },
    { colName: "NEC1_Desc", colText: "NEC1 Desc", sortable: true, sorted: false, visible: false },
    { colName: "NEC1_LongDesc", colText: "NEC1 LongDesc", sortable: true, sorted: false, visible: false },
    { colName: "NEC2_Code", colText: "NEC2 Code", sortable: true, sorted: false, visible: false },
    { colName: "NEC2_desc", colText: "NEC2 desc", sortable: true, sorted: false, visible: false },
    { colName: "NEC2_LongDesc", colText: "NEC2 LongDesc", sortable: true, sorted: false, visible: false },
    { colName: "NEC3_Code", colText: "NEC3 Code", sortable: true, sorted: false, visible: false },
    { colName: "NEC3_Desc", colText: "NEC3 Desc", sortable: true, sorted: false, visible: false },
    { colName: "NEC3_LongDesc", colText: "NEC3 LongDesc", sortable: true, sorted: false, visible: false },
    { colName: "NEC4_Code", colText: "NEC4 Code", sortable: true, sorted: false, visible: false },
    //{ colName: "NEC4_Desc", colText: "NEC4 Desc", sortable: true, sorted: false, visible: false },
    { colName: "NEC4_LongDesc", colText: "NEC4 LongDesc", sortable: true, sorted: false, visible: false },

    { colName: "CH_Segment_Code", colText: "CH Segment Code", sortable: true, sorted: false, visible: false },
    { colName: "CH_Segment_Desc", colText: "CH Segment Desc", sortable: true, sorted: false, visible: false },

      { colName: "WHO1_Code", colText: "WHO1 Code", sortable: true, sorted: false, visible: false },
    { colName: "WHO1_Desc", colText: "WHO1 Desc", sortable: true, sorted: false, visible: false },
    { colName: "WHO2_Code", colText: "WHO2 Code", sortable: true, sorted: false, visible: false },
    { colName: "WHO2_Desc", colText: "WHO2 Desc", sortable: true, sorted: false, visible: false },
    { colName: "WHO3_Code", colText: "WHO3 Code", sortable: true, sorted: false, visible: false },
    { colName: "WHO3_Desc", colText: "WHO3 Desc", sortable: true, sorted: false, visible: false },
    { colName: "WHO4_Code", colText: "WHO4 Code", sortable: true, sorted: false, visible: false },

    { colName: "WHO4_Desc", colText: "WHO4 Desc", sortable: true, sorted: false, visible: false },
    { colName: "WHO5_Code", colText: "WHO5 Code", sortable: true, sorted: false, visible: false },
    { colName: "WHO5_Desc", colText: "WHO5 Desc", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs1", colText: "FRM Flgs1", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs1_Desc", colText: "FRM Flgs1 Desc", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs2", colText: "FRM Flgs2", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs2_Desc", colText: "FRM Flgs2 Desc", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs3", colText: "FRM Flgs3", sortable: true, sorted: false, visible: false },
    //{ colName: "Frm_Flgs3_Desc", colText: "Frm_Flgs3_Desc", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs4", colText: "FRM Flgs4", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs4_Desc", colText: "FRM Flgs4 Desc", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs5", colText: "FRM Flgs5", sortable: true, sorted: false, visible: false },
    //{ colName: "FRM_Flgs5_Desc", colText: "FRM_Flgs5_Desc", sortable: true, sorted: false, visible: false },
    { colName: "FRM_Flgs6", colText: "FRM Flgs6", sortable: true, sorted: false, visible: false },

    { colName: "Compound_Indicator", colText: "Compound Indicator", sortable: true, sorted: false, visible: false },
    { colName: "Compound_Ind_Desc", colText: "Compound Ind_Desc", sortable: true, sorted: false, visible: false },
    { colName: "PBS_Formulary", colText: "PBS Formulary", sortable: true, sorted: false, visible: false },
    { colName: "PBS_Formulary_Date", colText: "PBS Formulary Date", sortable: true, sorted: false, visible: false },
    { colName: "Poison_Schedule", colText: "Poison Schedule", sortable: true, sorted: false, visible: false },
    { colName: "Poison_Schedule_Desc", colText: "Poison Schedule Desc", sortable: true, sorted: false, visible: false },
    { colName: "Stdy_Ind1_Code", colText: "Stdy Ind1 Code", sortable: true, sorted: false, visible: false },
    { colName: "Study_Indicators1", colText: "Study Indicators1", sortable: true, sorted: false, visible: false },
    { colName: "Stdy_Ind2_Code", colText: "Stdy Ind2 Code", sortable: true, sorted: false, visible: false },
    { colName: "Study_Indicators2", colText: "Study Indicators2", sortable: true, sorted: false, visible: false },
    { colName: "Stdy_Ind3_Code", colText: "Stdy Ind3 Code", sortable: true, sorted: false, visible: false },
    { colName: "Study_Indicators3", colText: "Study Indicators3", sortable: true, sorted: false, visible: false },
    { colName: "Stdy_Ind4_Code", colText: "Stdy Ind4 Code", sortable: true, sorted: false, visible: false },
    { colName: "Study_Indicators4", colText: "Study Indicators4", sortable: true, sorted: false, visible: false },

    { colName: "Stdy_Ind5_Code", colText: "Stdy Ind5 Code", sortable: true, sorted: false, visible: false },
    { colName: "Study_Indicators5", colText: "Study Indicators5", sortable: true, sorted: false, visible: false },
    { colName: "Stdy_Ind6_Code", colText: "Stdy Ind6 Code", sortable: true, sorted: false, visible: false },
    { colName: "Study_Indicators6", colText: "Study Indicators6", sortable: true, sorted: false, visible: false },
    { colName: "PackLaunch", colText: "Pack Launch", sortable: true, sorted: false, visible: false },
    { colName: "Prod_lch", colText: "Prod lch", sortable: true, sorted: false, visible: false },
    { colName: "Org_Code", colText: "Org Code", sortable: true, sorted: false, visible: false },
    { colName: "Org_Abbr", colText: "Org Abbr", sortable: true, sorted: false, visible: false },
    { colName: "Org_Short_Name", colText: "Org Short Name", sortable: true, sorted: false, visible: false },
    //{ colName: "Org_Long_Name", colText: "Org_Long_Name", sortable: true, sorted: false, visible: false },
    { colName: "Out_td_dt", colText: "Out td dt", sortable: true, sorted: false, visible: false },
    { colName: "Prtd_Price", colText: "Prtd Price", sortable: true, sorted: false, visible: false },
    { colName: "pk_size", colText: "pk size", sortable: true, sorted: false, visible: false },
    { colName: "vol_wt_uns", colText: "vol wt uns", sortable: true, sorted: false, visible: false },

    { colName: "vol_wt_meas", colText: "vol wt meas", sortable: true, sorted: false, visible: false },
    { colName: "strgh_uns", colText: "strgh uns", sortable: true, sorted: false, visible: false },
    { colName: "strgh_meas", colText: "strgh meas", sortable: true, sorted: false, visible: false },
    { colName: "Conc_Unit", colText: "Conc Unit", sortable: true, sorted: false, visible: false },
    { colName: "Conc_Meas", colText: "Conc Meas", sortable: true, sorted: false, visible: false },
    { colName: "Additional_Strength", colText: "Additional Strength", sortable: true, sorted: false, visible: false },
    { colName: "Additional_Pack_Info", colText: "Additional Pack Info", sortable: true, sorted: false, visible: false },
    { colName: "Recommended_Retail_Price", colText: "Recommended Retail Price", sortable: true, sorted: false, visible: false },
    { colName: "Ret_Price_Effective_Date", colText: "Ret Price Effective_Date", sortable: true, sorted: false, visible: false },
    { colName: "Editable_Pack_Description", colText: "Editable Pack Description", sortable: true, sorted: false, visible: false },
    
    { colName: "Trade_Product_Pack_ID", colText: "Trade Product Pack_ID", sortable: true, sorted: false, visible: false },
    { colName: "Form_Desc_Abbr", colText: "Form Desc Abbr", sortable: true, sorted: false, visible: false },
    { colName: "Form_Desc_Short", colText: "Form Desc Short", sortable: true, sorted: false, visible: false },

    { colName: "Form_Desc_Long", colText: "Form Desc Long", sortable: true, sorted: false, visible: false },
    { colName: "NFC1_Code", colText: "NFC1 Code", sortable: true, sorted: false, visible: false },
    { colName: "NFC1_Desc", colText: "NFC1 Desc", sortable: true, sorted: false, visible: false },
    { colName: "NFC2_Code", colText: "NFC2 Code", sortable: true, sorted: false, visible: false },
    { colName: "NFC2_Desc", colText: "NFC2 Desc", sortable: true, sorted: false, visible: false },
    { colName: "NFC3_Code", colText: "NFC3 Code", sortable: true, sorted: false, visible: false },
    { colName: "NFC3_Desc", colText: "NFC3 Desc", sortable: true, sorted: false, visible: false },
    { colName: "Price_Effective_Date", colText: "Price Effective Date", sortable: true, sorted: false, visible: false },
    { colName: "Last_amd", colText: "Last amd", sortable: true, sorted: false, visible: false },
    { colName: "PBS_Start_Date", colText: "PBS Start Date", sortable: true, sorted: false, visible: false },
    { colName: "PBS_End_Date", colText: "PBS End Date", sortable: true, sorted: false, visible: false },
    { colName: "Supplier_Code", colText: "Supplier Code", sortable: true, sorted: false, visible: false },
    { colName: "Supplier_Product_Code", colText: "Supplier Product Code", sortable: true, sorted: false, visible: false }
];