CREATE TABLE [dbo].[AU9_CLIENT_TERR_TEMP] (
    [CLIENT_TERR_ID]       BIGINT       NULL,
    [CLIENT_TERR_VERS_NBR] INT          NULL,
    [OTLT_CD]              VARCHAR (30) NULL,
    [LVL_1_TERR_CD]        VARCHAR (30) NULL,
    [LVL_1_TERR_NM]        VARCHAR (50) NULL,
    [LVL_2_TERR_CD]        VARCHAR (30) NULL,
    [LVL_2_TERR_NM]        VARCHAR (50) NULL,
    [LVL_3_TERR_CD]        VARCHAR (30) NULL,
    [LVL_3_TERR_NM]        VARCHAR (50) NULL,
    [LVL_4_TERR_CD]        VARCHAR (30) NULL,
    [LVL_4_TERR_NM]        VARCHAR (50) NULL,
    [LVL_5_TERR_CD]        VARCHAR (30) NULL,
    [LVL_5_TERR_NM]        VARCHAR (50) NULL,
    [LVL_6_TERR_CD]        VARCHAR (30) NULL,
    [LVL_6_TERR_NM]        VARCHAR (50) NULL,
    [LVL_7_TERR_CD]        VARCHAR (30) NULL,
    [LVL_7_TERR_NM]        VARCHAR (50) NULL,
    [LVL_8_TERR_CD]        VARCHAR (30) NULL,
    [LVL_8_TERR_NM]        VARCHAR (50) NULL
);

