CREATE TABLE [dbo].[excluded_dimproduct_expanded_19012018] (
    [Fcc]               INT           NULL,
    [Pack_cd]           SMALLINT      NULL,
    [PFC]               VARCHAR (15)  NULL,
    [NEC1_Code]         VARCHAR (30)  NULL,
    [NEC2_Code]         VARCHAR (30)  NULL,
    [NEC3_Code]         VARCHAR (30)  NULL,
    [NEC4_Code]         VARCHAR (30)  NULL,
    [Pack_Description]  VARCHAR (80)  NULL,
    [Stdy_Ind1_Code]    CHAR (1)      NULL,
    [Study_Indicators1] VARCHAR (30)  NULL,
    [Stdy_Ind2_Code]    CHAR (1)      NULL,
    [Study_Indicators2] VARCHAR (30)  NULL,
    [Stdy_Ind3_Code]    CHAR (1)      NULL,
    [Study_Indicators3] VARCHAR (30)  NULL,
    [Stdy_Ind4_Code]    CHAR (1)      NULL,
    [Study_Indicators4] VARCHAR (30)  NULL,
    [Stdy_Ind5_Code]    CHAR (1)      NULL,
    [Study_Indicators5] VARCHAR (30)  NULL,
    [Stdy_Ind6_Code]    CHAR (1)      NULL,
    [Study_Indicators6] VARCHAR (30)  NULL,
    [out_td_dt]         DATETIME2 (7) NULL,
    [Rule]              NVARCHAR (50) NULL,
    [TIME_STAMP]        DATETIME      NULL,
    [ATC1_CODE]         VARCHAR (30)  NULL,
    [ATC2_CODE]         VARCHAR (30)  NULL,
    [ATC3_CODE]         VARCHAR (30)  NULL,
    [ATC4_CODE]         VARCHAR (30)  NULL,
    [Frm_Flgs3_Desc]    VARCHAR (50)  NULL,
    [Frm_Flgs5_Desc]    VARCHAR (50)  NULL,
    [Org_Long_Name]     VARCHAR (80)  NULL,
    [ProductName]       VARCHAR (18)  NULL
);

