CREATE TABLE [dbo].[LevelTerritory] (
    [TERRITORYID]         INT          NULL,
    [clientid]            INT          NULL,
    [LVL_1_TERR_TYP_NM]   VARCHAR (15) NULL,
    [LVL_2_TERR_TYP_NM]   VARCHAR (15) NULL,
    [LVL_3_TERR_TYP_NM]   VARCHAR (15) NULL,
    [LVL_4_TERR_TYP_NM]   VARCHAR (15) NULL,
    [LVL_5_TERR_TYP_NM]   VARCHAR (15) NULL,
    [LVL_6_TERR_TYP_NM]   VARCHAR (15) NULL,
    [LVL_7_TERR_TYP_NM]   VARCHAR (15) NULL,
    [LVL_8_TERR_TYP_NM]   VARCHAR (15) NULL,
    [TERR_LOWEST_LVL_NBR] INT          NULL
);

