CREATE TABLE [dbo].[RAW_TDW-ECP_DIM_PRODUCT] (
    [PackID]                    INT             NOT NULL,
    [Prod_cd]                   INT             NULL,
    [Pack_cd]                   SMALLINT        NULL,
    [PFC]                       VARCHAR (15)    NULL,
    [ProductName]               VARCHAR (18)    NULL,
    [Product_Long_Name]         VARCHAR (80)    NULL,
    [Pack_Description]          VARCHAR (80)    NULL,
    [Pack_Long_Name]            VARCHAR (194)   NULL,
    [FCC]                       INT             NULL,
    [ATC1_Code]                 VARCHAR (30)    NULL,
    [ATC1_Desc]                 NVARCHAR (50)   NULL,
    [ATC2_Code]                 VARCHAR (30)    NULL,
    [ATC2_Desc]                 NVARCHAR (50)   NULL,
    [ATC3_Code]                 VARCHAR (30)    NULL,
    [ATC3_Desc]                 NVARCHAR (50)   NULL,
    [ATC4_Code]                 VARCHAR (30)    NULL,
    [ATC4_Desc]                 NVARCHAR (50)   NULL,
    [NEC1_Code]                 VARCHAR (30)    NULL,
    [NEC1_Desc]                 VARCHAR (50)    NULL,
    [NEC1_LongDesc]             VARCHAR (80)    NULL,
    [NEC2_Code]                 VARCHAR (30)    NULL,
    [NEC2_desc]                 VARCHAR (50)    NULL,
    [NEC2_LongDesc]             VARCHAR (80)    NULL,
    [NEC3_Code]                 VARCHAR (30)    NULL,
    [NEC3_Desc]                 VARCHAR (50)    NULL,
    [NEC3_LongDesc]             VARCHAR (80)    NULL,
    [NEC4_Code]                 VARCHAR (30)    NULL,
    [NEC4_Desc]                 VARCHAR (50)    NULL,
    [NEC4_LongDesc]             VARCHAR (80)    NULL,
    [CH_Segment_Code]           VARCHAR (3)     NULL,
    [CH_Segment_Desc]           VARCHAR (50)    NULL,
    [WHO1_Code]                 VARCHAR (30)    NULL,
    [WHO1_Desc]                 VARCHAR (50)    NULL,
    [WHO2_Code]                 VARCHAR (30)    NULL,
    [WHO2_Desc]                 VARCHAR (50)    NULL,
    [WHO3_Code]                 VARCHAR (30)    NULL,
    [WHO3_Desc]                 VARCHAR (50)    NULL,
    [WHO4_Code]                 VARCHAR (30)    NULL,
    [WHO4_Desc]                 VARCHAR (50)    NULL,
    [WHO5_Code]                 VARCHAR (30)    NULL,
    [WHO5_Desc]                 VARCHAR (50)    NULL,
    [FRM_Flgs1]                 CHAR (30)       NULL,
    [FRM_Flgs1_Desc]            VARCHAR (50)    NULL,
    [FRM_Flgs2]                 CHAR (30)       NULL,
    [FRM_Flgs2_Desc]            VARCHAR (50)    NULL,
    [FRM_Flgs3]                 CHAR (30)       NULL,
    [Frm_Flgs3_Desc]            VARCHAR (50)    NULL,
    [FRM_Flgs4]                 CHAR (30)       NULL,
    [FRM_Flgs4_Desc]            VARCHAR (50)    NULL,
    [FRM_Flgs5]                 CHAR (30)       NULL,
    [FRM_Flgs5_Desc]            VARCHAR (50)    NULL,
    [FRM_Flgs6]                 CHAR (30)       NULL,
    [Compound_Indicator]        VARCHAR (12)    NULL,
    [Compound_Ind_Desc]         VARCHAR (15)    NULL,
    [PBS_Formulary]             VARCHAR (30)    NULL,
    [PBS_Formulary_Date]        DATETIME2 (7)   NULL,
    [Poison_Schedule]           VARCHAR (30)    NULL,
    [Poison_Schedule_Desc]      VARCHAR (35)    NULL,
    [Stdy_Ind1_Code]            CHAR (1)        NULL,
    [Study_Indicators1]         VARCHAR (30)    NULL,
    [Stdy_Ind2_Code]            CHAR (1)        NULL,
    [Study_Indicators2]         VARCHAR (30)    NULL,
    [Stdy_Ind3_Code]            CHAR (1)        NULL,
    [Study_Indicators3]         VARCHAR (30)    NULL,
    [Stdy_Ind4_Code]            CHAR (1)        NULL,
    [Study_Indicators4]         VARCHAR (30)    NULL,
    [Stdy_Ind5_Code]            CHAR (1)        NULL,
    [Study_Indicators5]         VARCHAR (30)    NULL,
    [Stdy_Ind6_Code]            CHAR (1)        NULL,
    [Study_Indicators6]         VARCHAR (30)    NULL,
    [PackLaunch]                DATETIME2 (7)   NULL,
    [Prod_lch]                  DATETIME2 (7)   NULL,
    [Org_Code]                  INT             NULL,
    [Org_Abbr]                  VARCHAR (20)    NULL,
    [Org_Short_Name]            VARCHAR (50)    NULL,
    [Org_Long_Name]             VARCHAR (80)    NULL,
    [Out_td_dt]                 DATETIME2 (7)   NULL,
    [pk_size]                   INT             NULL,
    [vol_wt_uns]                REAL            NULL,
    [vol_wt_meas]               VARCHAR (30)    NULL,
    [strgh_uns]                 REAL            NULL,
    [strgh_meas]                VARCHAR (30)    NULL,
    [Conc_Unit]                 NUMERIC (18, 2) NULL,
    [Conc_Meas]                 DECIMAL (16, 3) NULL,
    [Additional_Strength]       VARCHAR (4)     NULL,
    [Additional_Pack_Info]      VARCHAR (4)     NULL,
    [Recommended_Retail_Price]  NUMERIC (18, 2) NULL,
    [Ret_Price_Effective_Date]  DATETIME        NULL,
    [Editable_Pack_Description] VARCHAR (80)    NULL,
    [APN]                       VARCHAR (18)    NULL,
    [Trade_Product_Pack_ID]     VARCHAR (18)    NULL,
    [Form_Desc_Abbr]            VARCHAR (30)    NULL,
    [Form_Desc_Short]           VARCHAR (50)    NULL,
    [Form_Desc_Long]            VARCHAR (80)    NULL,
    [NFC1_Code]                 NVARCHAR (30)   NULL,
    [NFC1_Desc]                 NVARCHAR (50)   NULL,
    [NFC2_Code]                 NVARCHAR (30)   NULL,
    [NFC2_Desc]                 NVARCHAR (50)   NULL,
    [NFC3_Code]                 NVARCHAR (30)   NULL,
    [NFC3_Desc]                 NVARCHAR (50)   NULL,
    [Price_Effective_Date]      DATETIME        NULL,
    [Last_amd]                  DATETIME2 (7)   NULL,
    [PBS_Start_Date]            DATETIME2 (7)   NULL,
    [PBS_End_Date]              DATETIME2 (7)   NULL,
    [Supplier_Code]             NUMERIC (15)    NULL,
    [Supplier_Product_Code]     VARCHAR (20)    NULL,
    [pack_del_indicator]        CHAR (1)        NULL,
    [Prtd_Price]                NUMERIC (16, 3) NULL
);



